package com.proje.insert4;

import java.sql.SQLException;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.proje.DBConnection;

public class DBProcesses {
	
public static void savePersonel(Personel personel){
		
		String sorgu = "INSERT INTO personel(personelId,adi,soyadi,dogumYili,personelNumarasi) VALUES(?,?,?,?,?)";
		
		Logger logger = LogManager.getLogger();
		
		Connection connection = DBConnection.getConnection();
		
		PreparedStatement preparedStatement = null;
		
		try {
			preparedStatement = (PreparedStatement) connection.prepareStatement(sorgu);
			preparedStatement.setInt(1, personel.getPersonelId());
			preparedStatement.setString(2, personel.getAdi());
			preparedStatement.setString(3, personel.getSoyadi());
			preparedStatement.setInt(4, personel.getDogumYili());
			preparedStatement.setString(5, personel.getOkulNumarasi());
			
			preparedStatement.executeUpdate();
			
			logger.info("Personel baþarýyla eklendi.");
			
		} catch (SQLException e) {
			logger.warn("Personel eklenirken hata oluþtu.");
		}
		finally {
			DBConnection.closeConnection(connection, preparedStatement);
		}
		
	}

}
